version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: whatsup_zookeeper
    ports:
      - "2181:2181"
    networks:
      - whatsup_kafka_network
    volumes:
      - ./zookeeper_data:/data

  kafka:
    image: wurstmeister/kafka:latest
    container_name: whatsup_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "chat-messages:1:1"
    depends_on:
      - zookeeper
    networks:
      - whatsup_kafka_network
    volumes:
      - ./kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: whatsup_kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Local Kafka Cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
    networks:
      - whatsup_kafka_network

networks:
  whatsup_kafka_network:
    driver: bridge
