version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: whatsup_postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: whatsup
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
